# Generated by Django 4.1.7 on 2023-03-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_1', models.CharField(max_length=50)),
                ('feature_2', models.CharField(max_length=50)),
                ('feature_3', models.CharField(max_length=50)),
                ('feature_4', models.CharField(max_length=50)),
                ('feature_5', models.CharField(max_length=50)),
                ('feature_6', models.CharField(max_length=50)),
                ('feature_7', models.CharField(max_length=50)),
                ('feature_8', models.CharField(max_length=50)),
                ('feature_9', models.CharField(max_length=50)),
                ('feature_10', models.CharField(max_length=50)),
                ('feature_11', models.CharField(max_length=50)),
                ('feature_12', models.CharField(max_length=50)),
                ('feature_13', models.CharField(max_length=50)),
                ('feature_14', models.CharField(max_length=50)),
                ('feature_15', models.CharField(max_length=50)),
                ('feature_16', models.CharField(max_length=50)),
                ('feature_17', models.CharField(max_length=50)),
                ('feature_18', models.CharField(max_length=50)),
                ('feature_19', models.CharField(max_length=50)),
                ('feature_20', models.CharField(max_length=50)),
            ],
        ),
    ]
